### ISSUE TITLE
属性名写错了.

### ISSUE THREAD

**Issue by hugohu** [yisibl/emmet-plus#3]
":befroe": ":befroe {\n\tcontent: '';\n\t|${child}\n}"
属性名写错了应该是.

我的使用方法: 直接在用户配置里添加相关的展开缩写内容.比撸主的改配置的相对来说方便一些.自己也可以自由添加跟编辑.如下图
![qq20140422100030](https://cloud.githubusercontent.com/assets/1574699/2760840/1a3594e6-c9c2-11e3-83db-d72084460f14.png)

**Comment by yisibl** [comment]
好的，修改一下，并增加一种使用方法
